# NFS CSI driver - provides NFS mount capability to the cluster
# The backup system (VolSync) uses native NFS mounts injected by Kyverno,
# not this CSI driver. This is for general-purpose NFS StorageClasses.

storageClass:
  create: false

controller:
  runOnControlPlane: false
  runOnMaster: false
