apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudnative-pg
commonLabels:
  app.kubernetes.io/name: immich-db
  app.kubernetes.io/managed-by: argocd
commonAnnotations:
  argocd.argoproj.io/sync-wave: "-5"
resources:
  - cluster.yaml
  - scheduled-backup.yaml
