apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: snapshot-controller

resources:
  - namespace.yaml

helmCharts:
  - name: snapshot-controller
    repo: https://piraeus.io/helm-charts/
    version: 5.0.2
    releaseName: snapshot-controller
    namespace: snapshot-controller
    valuesFile: values.yaml
    includeCRDs: true
