apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: volsync-system
resources:
  - namespace.yaml
  - volumesnapshotclass.yaml
helmCharts:
  - name: volsync
    repo: https://perfectra1n.github.io/volsync/charts
    version: 0.18.2
    releaseName: volsync
    namespace: volsync-system
    valuesFile: values.yaml
    includeCRDs: true
