apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflared
configMapGenerator:
  - name: config
    namespace: cloudflared
    files:
      - config.yaml
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ns.yaml
  - deployment.yaml
